import {
  Activity01Icon,
  AiViewIcon,
  Alert01Icon,
  Alert02Icon,
  Analytics01Icon,
  ArrowReloadHorizontalIcon,
  ArtificialIntelligence04Icon,
  Certificate01Icon,
  Certificate02Icon,
  ChartIncreaseIcon,
  ChartLineData02Icon,
  ChartUpIcon,
  CheckListIcon,
  ChipIcon,
  ClipboardIcon,
  CloudUploadIcon,
  CraneIcon,
  CustomerSupportIcon,
  Database01Icon,
  DocumentValidationIcon,
  DropletIcon,
  Factory01Icon,
  Factory02Icon,
  Fire02Icon,
  GasPipeIcon,
  MapsLocation01Icon,
  MentoringIcon,
  MoneyReceive01Icon,
  PipelineIcon,
  PuzzleIcon,
  Robot01Icon,
  SearchVisualIcon,
  Shield01Icon,
  SourceCodeIcon,
  Tap01Icon,
  WaterEnergyIcon,
  WaterPumpIcon,
  WorkflowSquare03Icon,
  Wrench01Icon,
  Calculator01Icon,
  ChartBreakoutSquareIcon,
  SecurityCheckIcon,
} from "@hugeicons/core-free-icons";
import type { IconSvgElement } from "@hugeicons/react";

export type Accent = "blue" | "orange" | "green";

export type SolutionPage = {
  slug: string;
  accent: Accent;
  hero: { eyebrow: string; headline: string; sub: string; primaryCta: { label: string; href: string }; secondaryCta: { label: string; href: string } };
  capabilities: { eyebrow: string; headline: string; sub: string; items: { title: string; body: string; icon: IconSvgElement }[] };
  difference: { eyebrow: string; headline: string; sub: string; cta: { label: string; href: string } };
  process: { eyebrow: string; headline: string; steps: { n: string; title: string; body: string }[] };
  related: { eyebrow: string; headline: string; items: { name: string; href: string; descriptor: string }[] };
  faq: { eyebrow: string; headline: string; items: { q: string; a: string }[] };
  cta: { eyebrow: string; headline: string; sub: string; cta: { label: string; href: string } };
};

export const solutionPages: Record<string, SolutionPage> = {
  "digital-transformation": {
    slug: "digital-transformation",
    accent: "orange",
    hero: {
      eyebrow: "Technology \u00b7 Digital Transformation",
      headline: "Off paper. Off legacy. Without the chaos.",
      sub: "Cloud migration, workflow automation, and IT strategy that move public agencies off paper and legacy systems, in fundable, phased stages that keep operations running.",
      primaryCta: { label: "Explore Solutions", href: "/solutions" },
      secondaryCta: { label: "Start a Project", href: "/contact" },
    },
    capabilities: {
      eyebrow: "Capabilities",
      headline: "Modernization sized to a public budget.",
      sub: "A phased move off paper and legacy tools, each stage delivering value on its own, so you never bet the whole budget on a single go-live.",
      items: [
        { title: "Systems Assessment", icon: CheckListIcon, body: "A clear-eyed audit of the tools, spreadsheets, and paper processes running your agency today, and what they cost." },
        { title: "Cloud Migration", icon: CloudUploadIcon, body: "Moving records, workflows, and reporting off local drives and legacy servers to secure, maintainable cloud systems." },
        { title: "Workflow Automation", icon: WorkflowSquare03Icon, body: "Replacing manual re-keying and paper routing with automated, auditable digital workflows." },
        { title: "GIS & Asset Data", icon: MapsLocation01Icon, body: "Turning drawings and as-builts into a single, queryable source of truth your whole team can use." },
        { title: "IoT & SCADA Integration", icon: ChipIcon, body: "Connecting field sensors and SCADA to your systems so operations data reaches the people who need it." },
        { title: "Training & Change Management", icon: MentoringIcon, body: "The human side: training, documentation, and phased rollout so new systems actually get adopted." },
      ],
    },
    difference: {
      eyebrow: "The Axiom Black difference",
      headline: "Transformation phased to a public budget.",
      sub: "Big-bang IT projects fail public agencies. We phase the move off paper and legacy systems into fundable stages, each one delivering value on its own, so you're never betting the whole budget on a single go-live, and staff are never left behind.",
      cta: { label: "See Our Technology Solutions", href: "/solutions" },
    },
    process: {
      eyebrow: "How a project runs",
      headline: "A phased path off paper, not a big-bang.",
      steps: [
        { n: "01", title: "Assess", body: "We map your current tools, data, and processes, and where the paper and rework actually pile up." },
        { n: "02", title: "Plan", body: "A phased roadmap sized to your budget and funding, with each stage delivering value on its own." },
        { n: "03", title: "Migrate", body: "We move systems and data in stages, keeping operations running the whole time." },
        { n: "04", title: "Adopt", body: "Training, documentation, and support so the new way of working sticks." },
      ],
    },
    related: {
      eyebrow: "Related solutions",
      headline: "The systems behind the transformation.",
      items: [
        { name: "Software Development", href: "/solutions/software-development", descriptor: "Custom dashboards and tools that turn your record drawings into living asset data." },
        { name: "AI & Machine Learning", href: "/solutions/ai-machine-learning", descriptor: "Predictive maintenance and AI assistants trained on your own operations." },
        { name: "Modeling", href: "/solutions/modeling", descriptor: "Hydraulic modeling that validates capacity and sizing decisions before they're drawn." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      headline: "Digital transformation questions, answered.",
      items: [
        { q: "How do I start a project with your team?", a: "Reach out through the contact form and we'll set up a scoped intro call. We start by mapping where the paper and rework pile up." },
        { q: "What services do you offer?", a: "Systems assessment, cloud migration, workflow automation, GIS and asset data, IoT/SCADA integration, and change management." },
        { q: "What types of businesses do you work with?", a: "Municipal utilities, authorities, public works departments, and government agencies, plus private clients in the water and infrastructure sector." },
        { q: "Do we have to replace everything at once?", a: "No, we phase the move into fundable stages, each delivering value on its own, so operations keep running throughout." },
        { q: "What about staff who aren't technical?", a: "Change management is built in: training, documentation, and phased rollout so new systems actually get adopted." },
        { q: "Can you work alongside our internal team?", a: "Absolutely. We embed with your staff and hand off systems your own people can run, partners, not vendors." },
        { q: "Is there a minimum project size or budget?", a: "No fixed minimum. We scope engagements to your budget and can start with an assessment and a phased plan." },
      ],
    },
    cta: {
      eyebrow: "Building the future",
      headline: "Still running the town on spreadsheets and a filing cabinet?",
      sub: "Tell us where the paper piles up. We'll show you the phased path off it, sized to your budget.",
      cta: { label: "Start Your Project", href: "/contact" },
    },
  },
  "ai-machine-learning": {
    slug: "ai-machine-learning",
    accent: "orange",
    hero: {
      eyebrow: "Technology \u00b7 AI & Machine Learning",
      headline: "AI that knows the difference between a demo and a water main.",
      sub: "Predictive maintenance, anomaly detection, and AI assistants trained on your own operations, built by a team that understands the physical system behind the data.",
      primaryCta: { label: "Explore Solutions", href: "/solutions" },
      secondaryCta: { label: "Start a Project", href: "/contact" },
    },
    capabilities: {
      eyebrow: "Capabilities",
      headline: "Applied AI, not aspirational AI.",
      sub: "Models tied to real decisions and real field data: the kind that survive contact with operations, not just a slide deck.",
      items: [
        { title: "Predictive Maintenance", icon: Wrench01Icon, body: "Models that flag pumps, mains, and equipment likely to fail, so crews fix problems before they become emergencies." },
        { title: "Anomaly Detection", icon: Alert02Icon, body: "Continuous monitoring of SCADA and sensor data to catch leaks, spikes, and faults the moment they start." },
        { title: "Computer Vision", icon: AiViewIcon, body: "Automated review of inspection video and imagery: pipe defects, meter reads, and site conditions scored at scale." },
        { title: "Forecasting & Demand", icon: ChartUpIcon, body: "Demand, flow, and consumption forecasts that inform capacity, staffing, and capital decisions." },
        { title: "AI Assistants", icon: Robot01Icon, body: "Assistants trained on your records and SOPs, so staff can ask questions instead of digging through binders." },
        { title: "Data Foundations", icon: Database01Icon, body: "The unglamorous groundwork (clean, connected, labeled data) that makes any model trustworthy." },
      ],
    },
    difference: {
      eyebrow: "The Axiom Black difference",
      headline: "AI grounded in the physical system.",
      sub: "Our models are built by a team that understands hydraulics and assets, not just algorithms: AI trained on the realities of your system, with engineers who can tell a real signal from noise, instead of a generic model that looks impressive in a demo and fails in the field.",
      cta: { label: "See Our Technology Solutions", href: "/solutions" },
    },
    process: {
      eyebrow: "How a project runs",
      headline: "From messy data to a model you can trust.",
      steps: [
        { n: "01", title: "Frame", body: "We start with the decision you're trying to make, not the model. If AI isn't the answer, we say so." },
        { n: "02", title: "Prepare", body: "We clean, connect, and label your data: the foundation every reliable model depends on." },
        { n: "03", title: "Build", body: "We train and validate against real field data, with engineers checking the results make physical sense." },
        { n: "04", title: "Operate", body: "The model ships into a tool your staff use daily, monitored and retrained as conditions change." },
      ],
    },
    related: {
      eyebrow: "Related solutions",
      headline: "Models are only as good as the system they watch.",
      items: [
        { name: "Modeling", href: "/solutions/modeling", descriptor: "Hydraulic modeling that validates capacity and sizing decisions before they're drawn." },
        { name: "Software Development", href: "/solutions/software-development", descriptor: "Custom dashboards and tools that turn your record drawings into living asset data." },
        { name: "Water", href: "/solutions/water", descriptor: "Distribution, treatment, and lead service line programs on the drinking water side." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      headline: "AI questions, answered.",
      items: [
        { q: "How do I start a project with your team?", a: "Reach out through the contact form and we'll set up a scoped intro call. We start with the decision you're trying to make, not the model." },
        { q: "What services do you offer?", a: "Predictive maintenance, anomaly detection, computer vision, forecasting, AI assistants, and the data foundations that make them reliable." },
        { q: "What types of businesses do you work with?", a: "Municipal utilities, authorities, public works departments, and government agencies, plus private clients in the water and infrastructure sector." },
        { q: "What if AI isn't the right answer?", a: "We'll tell you honestly. If a simpler tool or process fixes the problem, that's what we recommend. We're not here to sell a buzzword." },
        { q: "Do we own the models and data?", a: "Yes. You own the models, the code, and the data: nothing is locked inside a vendor platform." },
        { q: "Can you work alongside our internal team?", a: "Absolutely. We embed with your staff and hand off tools your own people can run, partners, not vendors." },
        { q: "Is there a minimum project size or budget?", a: "No fixed minimum. We scope engagements to the decision and available data, and can start with a focused pilot." },
      ],
    },
    cta: {
      eyebrow: "Building the future",
      headline: "Bring us a problem, not a buzzword.",
      sub: "Tell us what eats your team's time or budget. We'll tell you honestly whether AI is the answer.",
      cta: { label: "Start Your Project", href: "/contact" },
    },
  },
  "risk-assessment": {
    slug: "risk-assessment",
    accent: "blue",
    hero: {
      eyebrow: "Engineering \u00b7 Risk Assessment",
      headline: "Find the failure before it finds you.",
      sub: "Condition assessment, criticality scoring, and asset management planning, so limited capital goes to the assets most likely to fail and most costly to lose.",
      primaryCta: { label: "Explore Solutions", href: "/solutions" },
      secondaryCta: { label: "Start a Project", href: "/contact" },
    },
    capabilities: {
      eyebrow: "Capabilities",
      headline: "Know what's failing, and what to fix first.",
      sub: "Risk assessment grounded in field data and ranked by consequence: the foundation for a defensible, fundable capital plan.",
      items: [
        { title: "Condition Assessment", icon: SearchVisualIcon, body: "Field inspection and scoring of pipes, tanks, and treatment assets, so you know what's failing and what's next." },
        { title: "Criticality & Risk Scoring", icon: Alert01Icon, body: "Likelihood-and-consequence models that rank assets by risk, not just age, to focus limited capital." },
        { title: "Asset Management Plans", icon: ClipboardIcon, body: "WQAA- and audit-ready asset management plans that guide capital planning and stand up to scrutiny." },
        { title: "Resilience & Vulnerability", icon: Shield01Icon, body: "Flood, seismic, and single-point-of-failure analysis to harden the systems your community depends on." },
        { title: "Capital Improvement Planning", icon: ChartIncreaseIcon, body: "Prioritized, funded CIPs that turn risk findings into a defensible multi-year program." },
        { title: "Regulatory Compliance", icon: Certificate01Icon, body: "Reporting and documentation aligned with NJ WQAA and federal requirements, audit-ready every year." },
      ],
    },
    difference: {
      eyebrow: "The Axiom Black difference",
      headline: "Risk you can see, ranked, and act on.",
      sub: "Because our software team sits next to our engineers, risk findings don't die in a report. They become a live asset register and dashboard your staff can sort, filter, and act on, updated as conditions change.",
      cta: { label: "See Our Technology Solutions", href: "/solutions" },
    },
    process: {
      eyebrow: "How a project runs",
      headline: "From unknown risk to a funded plan.",
      steps: [
        { n: "01", title: "Inventory", body: "We assemble what you know (records, GIS, SCADA, and field data) into one picture of the system." },
        { n: "02", title: "Assess", body: "Condition inspection and criticality scoring rank every asset by real risk, not just age." },
        { n: "03", title: "Prioritize", body: "We turn findings into a prioritized, defensible capital plan aligned to your funding routes." },
        { n: "04", title: "Monitor", body: "A living asset register and dashboard keeps the risk picture current between studies." },
      ],
    },
    related: {
      eyebrow: "Related solutions",
      headline: "Good decisions start with good data.",
      items: [
        { name: "Modeling", href: "/solutions/modeling", descriptor: "Hydraulic modeling that validates capacity and sizing decisions before they're drawn." },
        { name: "Water", href: "/solutions/water", descriptor: "Distribution, treatment, and lead service line programs on the drinking water side." },
        { name: "Software Development", href: "/solutions/software-development", descriptor: "Custom dashboards and tools that turn your record drawings into living asset data." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      headline: "Risk assessment questions, answered.",
      items: [
        { q: "How do I start a project with your team?", a: "Reach out through the contact form and we'll set up a scoped intro call. We map the system and the data before proposing an assessment plan." },
        { q: "What services do you offer?", a: "Condition assessment, criticality and risk scoring, asset management plans, resilience analysis, capital planning, and regulatory compliance." },
        { q: "What types of businesses do you work with?", a: "Municipal utilities, authorities, public works departments, and government agencies, plus private clients in the water and infrastructure sector." },
        { q: "Do you work with clients outside of New Jersey?", a: "Our core work is in New Jersey, but we support projects regionally where our assessment and engineering experience applies." },
        { q: "Will the assessment meet WQAA requirements?", a: "Yes. Our asset management plans and reporting are built to satisfy New Jersey's Water Quality Accountability Act and federal requirements." },
        { q: "Can you work alongside our internal team?", a: "Absolutely. We embed with your staff and hand off a living asset register your own people can use, partners, not vendors." },
        { q: "Is there a minimum project size or budget?", a: "No fixed minimum. We scope engagements to the system and available funding, and can start with a focused assessment." },
      ],
    },
    cta: {
      eyebrow: "Building the future",
      headline: "Every system has a weakest point. Do you know yours?",
      sub: "A scoping call costs nothing. An emergency main break costs everything. Let's talk.",
      cta: { label: "Start Your Project", href: "/contact" },
    },
  },
  "data-analytics": {
    slug: "data-analytics",
    accent: "orange",
    hero: {
      eyebrow: "Technology \u00b7 Data Analytics & BI",
      headline: "Your data already knows. Ask it.",
      sub: "Dashboards, warehousing, and reporting that pull SCADA, GIS, billing, and work orders into one place, so budget meetings and compliance deadlines start with evidence instead of a scramble.",
      primaryCta: { label: "Explore Solutions", href: "/solutions" },
      secondaryCta: { label: "Start a Project", href: "/contact" },
    },
    capabilities: {
      eyebrow: "Capabilities",
      headline: "One version of the numbers.",
      sub: "Most agencies aren't short on data. They're short on a place where it agrees with itself. We build that place, then the views your staff and your board actually use.",
      items: [
        { title: "KPI Dashboards", icon: Analytics01Icon, body: "Live views of flow, non-revenue water, work order backlog, and compliance status, built for operators and elected officials alike." },
        { title: "Data Warehousing", icon: Database01Icon, body: "SCADA, GIS, billing, and CMMS pulled into one governed store, so every report starts from the same numbers." },
        { title: "Regulatory Reporting", icon: DocumentValidationIcon, body: "Recurring NJDEP, WQAA, and funding reports generated from source data, not rebuilt by hand each cycle." },
        { title: "Rate & Revenue Analysis", icon: Calculator01Icon, body: "Consumption, billing, and cost-of-service analysis that supports rate cases with defensible numbers." },
        { title: "Self-Service Analytics", icon: ChartBreakoutSquareIcon, body: "Tools and training so staff can answer their own questions instead of queuing behind one spreadsheet expert." },
        { title: "Data Quality & Governance", icon: SecurityCheckIcon, body: "Validation, definitions, and ownership: the unglamorous work that makes a dashboard trustworthy enough to act on." },
      ],
    },
    difference: {
      eyebrow: "The Axiom Black difference",
      headline: "Engineers read the dashboard first.",
      sub: "A BI consultant can chart whatever column you point at. Our analytics team sits next to the engineers who design and model these systems, so when a number looks wrong, someone here knows whether the pump, the sensor, or the query is lying.",
      cta: { label: "See Our Technology Solutions", href: "/solutions" },
    },
    process: {
      eyebrow: "How a project runs",
      headline: "From scattered exports to a single source of truth.",
      steps: [
        { n: "01", title: "Question", body: "We start from the decisions you make each month (rates, staffing, capital) and work backward to the data behind them." },
        { n: "02", title: "Connect", body: "SCADA, GIS, billing, and work order systems get wired into one governed store, with definitions agreed in writing." },
        { n: "03", title: "Build", body: "Dashboards and recurring reports ship in short iterations, reviewed by the people who will live with them." },
        { n: "04", title: "Hand Over", body: "Training, documentation, and support so your staff extend the reporting themselves, no standing invoice to change a chart." },
      ],
    },
    related: {
      eyebrow: "Related solutions",
      headline: "What good data makes possible.",
      items: [
        { name: "AI & Machine Learning", href: "/solutions/ai-machine-learning", descriptor: "Predictive maintenance and forecasting, once the data foundation is in place." },
        { name: "Digital Transformation", href: "/solutions/digital-transformation", descriptor: "Getting off paper and legacy systems so there is clean data to report on." },
        { name: "Software Development", href: "/solutions/software-development", descriptor: "Custom applications for the workflows a dashboard alone can't fix." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      headline: "Data analytics questions, answered.",
      items: [
        { q: "How do I start a project with your team?", a: "Reach out through the contact form. We begin with a short assessment of what data you hold, where it lives, and which recurring reports cost you the most time." },
        { q: "What services do you offer?", a: "KPI dashboards, data warehousing, regulatory and board reporting, rate and revenue analysis, self-service analytics, and data quality and governance work." },
        { q: "Our data is a mess. Is it too early for this?", a: "No, that's the normal starting point. Cleaning, connecting, and defining the data is part of the engagement, not a prerequisite for it." },
        { q: "Which tools do you build on?", a: "We work with what you already own where we can: Power BI, Tableau, or custom web dashboards, and recommend against new licenses when existing tools will do." },
        { q: "Can this feed our regulatory reporting?", a: "Yes. Recurring NJDEP, WQAA, and funding reports can be generated from the same source data, which is usually where the time savings show up first." },
        { q: "Who owns the dashboards afterward?", a: "You do. We document the models and train your staff so routine changes don't require us." },
        { q: "Is there a minimum project size or budget?", a: "No fixed minimum. Many agencies start with one dashboard tied to one painful monthly report, then expand." },
      ],
    },
    cta: {
      eyebrow: "Building the future",
      headline: "How long does your monthly report really take?",
      sub: "If the answer is measured in days, most of it can be automated. Let's look at where the time goes.",
      cta: { label: "Start Your Project", href: "/contact" },
    },
  },
  "software-development": {
    slug: "software-development",
    accent: "orange",
    hero: {
      eyebrow: "Technology \u00b7 Software Development",
      headline: "Software shaped to how your team actually works.",
      sub: "Custom applications, dashboards, and integrations built for public-sector and utility teams, designed around your workflows, not forced onto someone else's product.",
      primaryCta: { label: "Explore Solutions", href: "/solutions" },
      secondaryCta: { label: "Start a Project", href: "/contact" },
    },
    capabilities: {
      eyebrow: "Capabilities",
      headline: "Built to be used, documented to be kept.",
      sub: "Practical software your staff will actually adopt: well-documented, maintainable, and owned by you, not locked inside a vendor platform.",
      items: [
        { title: "Custom Applications", icon: SourceCodeIcon, body: "Purpose-built web apps for the workflows off-the-shelf tools never quite fit, designed around how your staff actually work." },
        { title: "Dashboards & Reporting", icon: Analytics01Icon, body: "Live dashboards and automated reports that turn scattered spreadsheets and SCADA feeds into decisions." },
        { title: "Legacy Modernization", icon: ArrowReloadHorizontalIcon, body: "Migrating aging systems and paper processes to maintainable, documented software, without losing institutional knowledge." },
        { title: "System Integrations", icon: PuzzleIcon, body: "Connecting GIS, SCADA, CMMS, and finance systems so data flows once and stays in sync." },
        { title: "AI & Automation", icon: ArtificialIntelligence04Icon, body: "Practical automation and AI assistants trained on your operations, from data entry to condition flagging." },
        { title: "Support & Maintenance", icon: CustomerSupportIcon, body: "Ongoing support, monitoring, and iteration: the software keeps working long after launch." },
      ],
    },
    difference: {
      eyebrow: "The Axiom Black difference",
      headline: "Software your engineers actually helped design.",
      sub: "Because our developers sit next to licensed engineers, the tools we build understand the domain: hydraulics, permitting, asset management, not just generic screens. That context is the difference between software that gets used and software that gets abandoned.",
      cta: { label: "Explore Solutions", href: "/solutions" },
    },
    process: {
      eyebrow: "How a build runs",
      headline: "You see working software every week, not a reveal at the end.",
      steps: [
        { n: "01", title: "Discover", body: "We map the workflow, the data, and the people, and agree on what success looks like before writing code." },
        { n: "02", title: "Prototype", body: "A clickable prototype puts the idea in front of your team early, so we fix direction cheaply." },
        { n: "03", title: "Build", body: "Short iterations ship working software you can try every week, no big-bang reveal at the end." },
        { n: "04", title: "Support", body: "Launch, training, and ongoing maintenance: the tool keeps evolving with your operations." },
      ],
    },
    related: {
      eyebrow: "Related solutions",
      headline: "Built on a foundation of real data.",
      items: [
        { name: "Modeling", href: "/solutions/modeling", descriptor: "Hydraulic modeling that validates capacity and sizing decisions before they're drawn." },
        { name: "Water", href: "/solutions/water", descriptor: "Distribution, treatment, and lead service line programs on the drinking water side." },
        { name: "AI & Machine Learning", href: "/solutions/ai-machine-learning", descriptor: "Predictive maintenance and AI assistants trained on your own operations." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      headline: "Development questions, answered.",
      items: [
        { q: "How do I start a project with your team?", a: "Reach out through the contact form and we'll set up a scoped intro call. We map the workflow and the data before proposing a build plan." },
        { q: "What services do you offer?", a: "Custom applications, dashboards and reporting, legacy modernization, system integrations, AI and automation, and ongoing support." },
        { q: "What types of businesses do you work with?", a: "Municipal utilities, authorities, public works departments, and government agencies, plus private clients in the water and infrastructure sector." },
        { q: "Do we own the software you build?", a: "Yes. You own the code and the data: nothing is locked inside a vendor platform, and everything ships documented." },
        { q: "Can you integrate with our existing systems?", a: "Yes, we connect GIS, SCADA, CMMS, and finance systems so data flows once and stays in sync." },
        { q: "Can you work alongside our internal team?", a: "Absolutely. We embed with your staff and work in your systems, partners, not vendors." },
        { q: "Is there a minimum project size or budget?", a: "No fixed minimum. We scope engagements to the workflow and available funding, and can start with a prototype." },
      ],
    },
    cta: {
      eyebrow: "Building the future",
      headline: "The tool your team needs doesn't exist yet. Let's fix that.",
      sub: "Describe the workflow that's driving your staff crazy. We'll scope what it takes to build the fix.",
      cta: { label: "Start Your Project", href: "/contact" },
    },
  },
  modeling: {
    slug: "modeling",
    accent: "blue",
    hero: {
      eyebrow: "Engineering \u00b7 Modeling",
      headline: "Know how your network behaves before you break ground.",
      sub: "Calibrated hydraulic models of your water distribution and sewer collection systems, so capacity questions, pressure problems, and growth decisions get answered with data instead of guesswork.",
      primaryCta: { label: "Explore Solutions", href: "/solutions" },
      secondaryCta: { label: "Start a Project", href: "/contact" },
    },
    capabilities: {
      eyebrow: "Capabilities",
      headline: "A digital twin of your system, kept honest.",
      sub: "Built on industry-standard platforms, calibrated against real field data, and maintained so the model stays true as your system changes.",
      items: [
        { title: "Water Distribution Models", icon: DropletIcon, body: "Full-network models for pressure, water age, and flow: the backbone for main sizing and system planning." },
        { title: "Sewer Collection Models", icon: PipelineIcon, body: "Gravity and pumped collection system models that expose surcharging, bottlenecks, and wet-weather behavior." },
        { title: "Fire Flow Analysis", icon: Fire02Icon, body: "Available fire flow mapped hydrant by hydrant, for ISO reviews, development approvals, and main replacement priorities." },
        { title: "Surge & Transient Analysis", icon: Activity01Icon, body: "Pressure transient studies for force mains and pump stations, protecting pipes and equipment from water hammer." },
        { title: "Permitting & Approvals", icon: DocumentValidationIcon, body: "NJDEP Treatment Works Approvals, NJPDES coordination, and local approvals managed start to finish." },
        { title: "Construction Administration", icon: CraneIcon, body: "Bidding support, shop drawing review, inspection, and closeout: the design team stays on through delivery." },
      ],
    },
    difference: {
      eyebrow: "The Axiom Black difference",
      headline: "Models that live past the report.",
      sub: "Most modeling engagements end with a PDF and a file nobody can open. Ours can end with a maintained digital twin: connected to your SCADA and GIS data, updated on a schedule, and queryable by your own staff through dashboards our software team builds.",
      cta: { label: "Explore Solutions", href: "/solutions" },
    },
    process: {
      eyebrow: "How a project runs",
      headline: "From scattered records to a calibrated answer machine.",
      steps: [
        { n: "01", title: "Scope", body: "Field investigation, survey coordination, and alternatives analysis to lock the right solution before design begins." },
        { n: "02", title: "Fund", body: "Cost estimates and documentation aligned to your funding route: NJEIT, USDA, or capital budget." },
        { n: "03", title: "Design & Permit", body: "Progressive design submissions, NJDEP permitting, and bid-ready plans, specs, and estimates." },
        { n: "04", title: "Build", body: "Bidding support, construction administration, and inspection through closeout, with digital record data delivered." },
      ],
    },
    related: {
      eyebrow: "Related solutions",
      headline: "Good design starts with good data.",
      items: [
        { name: "Modeling", href: "/solutions/modeling", descriptor: "Hydraulic modeling that validates capacity and sizing decisions before they're drawn." },
        { name: "Water", href: "/solutions/water", descriptor: "Distribution, treatment, and lead service line programs on the drinking water side." },
        { name: "Software Development", href: "/solutions/software-development", descriptor: "Custom dashboards and tools that turn your record drawings into living asset data." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      headline: "Modeling questions, answered.",
      items: [
        { q: "How do I start a project with your team?", a: "Reach out through the contact form and we'll set up a scoped intro call. We map the question your system keeps asking before proposing a modeling plan." },
        { q: "What services do you offer?", a: "Water distribution and sewer collection models, fire flow analysis, surge and transient studies, plus maintained digital twins connected to your SCADA and GIS." },
        { q: "What types of businesses do you work with?", a: "Municipal utilities, authorities, public works departments, and government agencies, plus private clients in the water and infrastructure sector." },
        { q: "Do you work with clients outside of New Jersey?", a: "Our core work is in New Jersey, but we support projects regionally where our modeling and engineering experience applies." },
        { q: "What modeling platforms do you use?", a: "We build on industry-standard platforms and calibrate against real field data, so the model reflects how your system actually behaves." },
        { q: "Can you work alongside our internal team?", a: "Absolutely. We embed with your staff and hand off a model your own people can query, partners, not vendors." },
        { q: "Is there a minimum project size or budget?", a: "No fixed minimum. We scope engagements to the question and available funding, and can start with a focused study." },
      ],
    },
    cta: {
      eyebrow: "Building the future",
      headline: "Stop guessing. Start modeling.",
      sub: "Tell us the question your system keeps asking. We'll build the model that answers it.",
      cta: { label: "Start Your Project", href: "/contact" },
    },
  },
  design: {
    slug: "design",
    accent: "blue",
    hero: {
      eyebrow: "Engineering \u00b7 Design",
      headline: "From concept to creation, engineered with precision.",
      sub: "Collection systems, lift stations, force mains, and treatment plants: Axiom Black delivers permitted, bid-ready wastewater and civil designs that contractors can build and councils can fund.",
      primaryCta: { label: "Explore Solutions", href: "/solutions" },
      secondaryCta: { label: "Start a Project", href: "/contact" },
    },
    capabilities: {
      eyebrow: "Capabilities",
      headline: "Design work that survives contact with construction.",
      sub: "Plans, specifications, and estimates built from field reality, with permitting and construction administration handled by the same team that drew them.",
      items: [
        { title: "Collection Systems", icon: PipelineIcon, body: "Gravity sewer design, extensions, and rehabilitation, sized, sloped, and staged for real streets and real budgets." },
        { title: "Lift & Pump Stations", icon: WaterPumpIcon, body: "New stations and rehabilitations: wet well sizing, pump selection, controls, and standby power designed for operators." },
        { title: "Force Mains", icon: GasPipeIcon, body: "Alignment studies, surge analysis, and pipe material selection for force mains that stay serviceable for decades." },
        { title: "Treatment Plants", icon: Factory01Icon, body: "Wastewater treatment upgrades and process improvements designed around compliance limits and operating staff." },
        { title: "Permitting & Approvals", icon: DocumentValidationIcon, body: "NJDEP Treatment Works Approvals, NJPDES coordination, and local approvals managed start to finish." },
        { title: "Construction Administration", icon: CraneIcon, body: "Bidding support, shop drawing review, inspection, and closeout: the design team stays on through delivery." },
      ],
    },
    difference: {
      eyebrow: "The Axiom Black difference",
      headline: "Designs that arrive with their own data.",
      sub: "Every design project can close out with more than record drawings: digitized asset records, GIS-ready inventories, and dashboards your operators actually use. The as-builts become the beginning of your asset management program, not a PDF in a drawer.",
      cta: { label: "See Our Technology Solutions", href: "/solutions" },
    },
    process: {
      eyebrow: "How a project runs",
      headline: "From first call to final closeout.",
      steps: [
        { n: "01", title: "Scope", body: "Field investigation, survey coordination, and alternatives analysis to lock the right solution before design begins." },
        { n: "02", title: "Fund", body: "Cost estimates and documentation aligned to your funding route: NJEIT, USDA, or capital budget." },
        { n: "03", title: "Design & Permit", body: "Progressive design submissions, NJDEP permitting, and bid-ready plans, specs, and estimates." },
        { n: "04", title: "Build", body: "Bidding support, construction administration, and inspection through closeout, with digital record data delivered." },
      ],
    },
    related: {
      eyebrow: "Related solutions",
      headline: "Good design starts with good data.",
      items: [
        { name: "Modeling", href: "/solutions/modeling", descriptor: "Hydraulic modeling that validates capacity and sizing decisions before they're drawn." },
        { name: "Water", href: "/solutions/water", descriptor: "Distribution, treatment, and lead service line programs on the drinking water side." },
        { name: "Software Development", href: "/solutions/software-development", descriptor: "Custom dashboards and tools that turn your record drawings into living asset data." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      headline: "Design project questions, answered.",
      items: [
        { q: "How do I start a project with your team?", a: "Reach out through the contact form and we'll set up a scoped intro call. We map the problem, constraints, and funding path before proposing a design plan." },
        { q: "What services do you offer?", a: "Full civil and wastewater design: collection systems, lift and pump stations, force mains, treatment plants, permitting, and construction administration." },
        { q: "What types of businesses do you work with?", a: "Municipal utilities, authorities, public works departments, and government agencies, plus private clients in the water and infrastructure sector." },
        { q: "Do you work with clients outside of New Jersey?", a: "Our core work is in New Jersey, but we support projects regionally where our design and permitting experience applies." },
        { q: "Do you handle permitting?", a: "Yes, NJDEP Treatment Works Approvals, NJPDES coordination, and local approvals are managed by the same team that produced the design." },
        { q: "Can you work alongside our internal team?", a: "Absolutely. We embed with your staff and work in your systems, partners, not vendors." },
        { q: "Is there a minimum project size or budget?", a: "No fixed minimum. We scope engagements to the problem and available funding, and can start with an assessment." },
      ],
    },
    cta: {
      eyebrow: "Building the future",
      headline: "Have a project on the books for next budget cycle?",
      sub: "The best time to start design is before the funding deadline gets close. Let's scope it now.",
      cta: { label: "Start Your Project", href: "/contact" },
    },
  },
  water: {
    slug: "water",
    accent: "blue",
    hero: {
      eyebrow: "Engineering · Water",
      headline: "Water systems your community can depend on.",
      sub: "From source to tap, Axiom Black plans, designs, and delivers the drinking-water and wastewater infrastructure that keeps communities running, with the funding and compliance work built in.",
      primaryCta: { label: "Explore Solutions", href: "/solutions" },
      secondaryCta: { label: "Start a Project", href: "/contact" },
    },
    capabilities: {
      eyebrow: "Capabilities",
      headline: "Everything between the source and the tap.",
      sub: "Full-lifecycle water engineering: planning, design, funding support, and construction administration, delivered by one accountable team.",
      items: [
        { title: "Distribution Systems", icon: WaterEnergyIcon, body: "Water main design, replacement, and looping studies: pressure, fire flow, and age-based prioritization included." },
        { title: "Treatment Facilities", icon: Factory02Icon, body: "Upgrades, rehabilitation, and process improvements for water treatment plants, designed for compliance and operability." },
        { title: "Lead Service Line Programs", icon: Tap01Icon, body: "Inventory, verification, and replacement program management aligned with federal lead rules and New Jersey's replacement mandate." },
        { title: "WQAA Compliance", icon: Certificate02Icon, body: "Asset management plans and reporting under New Jersey's Water Quality Accountability Act, audit-ready, every year." },
        { title: "Hydraulic Modeling", icon: ChartLineData02Icon, body: "Calibrated network models that answer the hard questions (capacity, pressure zones, and growth scenarios) before construction." },
        { title: "Funding & Grant Support", icon: MoneyReceive01Icon, body: "Application engineering and documentation for NJEIT (I-Bank) and USDA Rural Development funded projects." },
      ],
    },
    difference: {
      eyebrow: "The Axiom Black difference",
      headline: "Water engineering with a data layer built in.",
      sub: "Because our software team sits next to our engineers, every water project can ship with more than drawings: digitized asset inventories, live dashboards, and AI-assisted condition tracking, the foundation your WQAA reporting and capital planning run on.",
      cta: { label: "See Our Technology Solutions", href: "/solutions" },
    },
    process: {
      eyebrow: "How a project runs",
      headline: "From first call to final closeout.",
      steps: [
        { n: "01", title: "Scope", body: "Field investigation, survey coordination, and alternatives analysis to lock the right solution before design begins." },
        { n: "02", title: "Fund", body: "Cost estimates and documentation aligned to your funding route: NJEIT, USDA, or capital budget." },
        { n: "03", title: "Design & Permit", body: "Progressive design submissions, NJDEP permitting, and bid-ready plans, specs, and estimates." },
        { n: "04", title: "Build", body: "Bidding support, construction administration, and inspection through closeout, with digital record data delivered." },
      ],
    },
    related: {
      eyebrow: "Related solutions",
      headline: "Good design starts with good data.",
      items: [
        { name: "Modeling", href: "/solutions/modeling", descriptor: "Hydraulic modeling that validates capacity and sizing decisions before they're drawn." },
        { name: "Water", href: "/solutions/water", descriptor: "Distribution, treatment, and lead service line programs on the drinking water side." },
        { name: "Software Development", href: "/solutions/software-development", descriptor: "Custom dashboards and tools that turn your record drawings into living asset data." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      headline: "Water project questions, answered.",
      items: [
        { q: "How do I start a project with your team?", a: "Reach out through the contact form and we'll set up a scoped intro call. We map the problem, constraints, and funding path before proposing a plan." },
        { q: "What services do you offer?", a: "Full-lifecycle water engineering: distribution and treatment design, lead service line programs, WQAA compliance, hydraulic modeling, and funding support." },
        { q: "What types of businesses do you work with?", a: "Municipal utilities, water authorities, public works departments, and government agencies, plus private clients in the water sector." },
        { q: "Do you work with clients outside of New Jersey?", a: "Our core work is in New Jersey, but we support projects regionally where our engineering and funding experience applies." },
        { q: "Do you offer ongoing operational support?", a: "Yes. Beyond delivery we offer asset-management support, monitoring dashboards, and iterative improvements to the systems we build." },
        { q: "Can you work alongside our internal team?", a: "Absolutely. We embed with your staff and work in your systems, partners, not vendors." },
        { q: "Is there a minimum project size or budget?", a: "No fixed minimum. We scope engagements to the problem and available funding, and can start with an assessment." },
      ],
    },
    cta: {
      eyebrow: "Building the future",
      headline: "Your water system deserves a partner, not a vendor.",
      sub: "Tell us about your system. We'll tell you honestly what it needs and how to fund it.",
      cta: { label: "Start Your Project", href: "/contact" },
    },
  },
};
